export interface CostCode {
  code: string;
  name: string;
  fullName: string;
}

export const COST_CODES: CostCode[] = [
  { code: "1000L", name: "PERMITS AND FEES", fullName: "1000L PERMITS AND FEES" },
  { code: "1100L", name: "DESIGN & SELECTIONS", fullName: "1100L DESIGN & SELECTIONS" },
  { code: "1200L", name: "CLEARING & GRADING", fullName: "1200L CLEARING & GRADING" },
  { code: "1300L", name: "DEMOLITION & DISPOSAL", fullName: "1300L DEMOLITION & DISPOSAL" },
  { code: "1400L", name: "UTILITY CONNECTIONS", fullName: "1400L UTILITY CONNECTIONS" },
  { code: "1500L", name: "SANITARY/SEPTIC", fullName: "1500L SANITARY/SEPTIC" },
  { code: "1600L", name: "WATER/WELL INSTALLATION", fullName: "1600L WATER/WELL INSTALLATION" },
  { code: "2000L", name: "EXCAVATION", fullName: "2000L EXCAVATION" },
  { code: "2100L", name: "FOOTING AND FOUNDATIONS", fullName: "2100L FOOTING AND FOUNDATIONS" },
  { code: "3000L", name: "FRAMING", fullName: "3000L FRAMING" },
  { code: "3050L", name: "DECORATIVE BEAMS", fullName: "3050L DECORATIVE BEAMS" },
  { code: "3100L", name: "STEEL", fullName: "3100L STEEL" },
  { code: "3200L", name: "WINDOWS AND DOORS", fullName: "3200L WINDOWS AND DOORS" },
  { code: "3250L", name: "OVERHEAD DOORS", fullName: "3250L OVERHEAD DOORS" },
  { code: "3300L", name: "ROOFING", fullName: "3300L ROOFING" },
  { code: "3400L", name: "CONCRETE FLOORS AND PORCH", fullName: "3400L CONCRETE FLOORS AND PORCH" },
  { code: "3500L", name: "ROUGH PLUMBING", fullName: "3500L ROUGH PLUMBING" },
  { code: "3600L", name: "ROUGH ELECTRICAL", fullName: "3600L ROUGH ELECTRICAL" },
  { code: "3650L", name: "SMART HOME", fullName: "3650L SMART HOME" },
  { code: "3700L", name: "ROUGH HVAC", fullName: "3700L ROUGH HVAC" },
  { code: "3750L", name: "FIREPLACES", fullName: "3750L FIREPLACES" },
  { code: "3800L", name: "MASONRY", fullName: "3800L MASONRY" },
  { code: "3900L", name: "SOFFIT FASCIA TROUGH", fullName: "3900L SOFFIT FASCIA TROUGH" },
  { code: "3950L", name: "SIDING & EXTERIOR TRIM", fullName: "3950L SIDING & EXTERIOR TRIM" },
  { code: "4000L", name: "INSULATION", fullName: "4000L INSULATION" },
  { code: "4100L", name: "DRYWALL", fullName: "4100L DRYWALL" },
  { code: "4200L", name: "PAINT", fullName: "4200L PAINT" },
  { code: "4300L", name: "INTERIOR DOORS & TRIM", fullName: "4300L INTERIOR DOORS & TRIM" },
  { code: "4350L", name: "STAIRS", fullName: "4350L STAIRS" },
  { code: "4351L", name: "INTERIOR RAILINGS", fullName: "4351L INTERIOR RAILINGS" },
  { code: "4400L", name: "FLOORING", fullName: "4400L FLOORING" },
  { code: "4500L", name: "CERAMIC TILE", fullName: "4500L CERAMIC TILE" },
  { code: "4600L", name: "CABINETRY & COUNTERTOPS", fullName: "4600L CABINETRY & COUNTERTOPS" },
  { code: "4650L", name: "BACKSPLASH", fullName: "4650L BACKSPLASH" },
  { code: "4700L", name: "FINISH PLUMBING", fullName: "4700L FINISH PLUMBING" },
  { code: "4750L", name: "SHOWER DOORS MIRRORS & ACCS", fullName: "4750L SHOWER DOORS MIRRORS & ACCS" },
  { code: "4800L", name: "FINISH ELECTRICAL", fullName: "4800L FINISH ELECTRICAL" },
  { code: "4900L", name: "FINISH HVAC", fullName: "4900L FINISH HVAC" },
  { code: "4950L", name: "APPLIANCES", fullName: "4950L APPLIANCES" },
  { code: "5000L", name: "BUILDING CLEAN-UP", fullName: "5000L BUILDING CLEAN-UP" },
  { code: "5100L", name: "LANDSCAPING", fullName: "5100L LANDSCAPING" },
  { code: "5200L", name: "DECKS AND FENCING", fullName: "5200L DECKS AND FENCING" },
  { code: "5300L", name: "EXTERIOR RAILINGS", fullName: "5300L EXTERIOR RAILINGS" },
  { code: "6000L", name: "EXTRA WORK ABOVE QUOTE", fullName: "6000L EXTRA WORK ABOVE QUOTE" },
  { code: "6100L", name: "HANDYPERSON WORK", fullName: "6100L HANDYPERSON WORK" },
  { code: "6200L", name: "SERVICE & WARRANTY WORK", fullName: "6200L SERVICE & WARRANTY WORK" },
  { code: "8200", name: "STAT HOLIDAY", fullName: "8200 STAT HOLIDAY" },
  { code: "8600", name: "VACATION TIME", fullName: "8600 VACATION TIME" },
  { code: "8800", name: "SITE VISIT", fullName: "8800 SITE VISIT" }
];
